addons:
    apt:
        packages:
            - python-pygments

install:
    - rm -rf public || exit 0

script:
    - binaries/hugo --theme=blogus
    - echo 'www.inoyatov.com' > public/CNAME

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: public
    on:
        branch: ghpages
